# Generated by Django 4.2.4 on 2023-08-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_auth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['phonenumber'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
